<a href="https://colab.research.google.com/github/HenriqueHideaki/MachineLearning/blob/main/ImdbRanking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.kaggle.com/datasets/sankha1998/tmdb-top-10000-popular-movies-dataset?select=TMDb_updated.CSV
https://www.kaggle.com/datasets/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [51]:
import pandas as pd

In [60]:
data = pd.read_csv('/content/Popular Movies TV shows from Prime Videos Netflix version_3.csv')

data.drop(columns = ['Unnamed: 0', 'ID'], inplace = True)
data.rename(columns = {'Title': 'Título do Filme', 'Genre': 'Gênero', 'Rating': 'Faixa Etária', 'Year': 'Ano'})

,Título do Filme,Ano,Faixa Etária,IMDb,Rotten Tomatoes,Gênero,Netflix,Amazon Prime Video
0,Terminator: Dark Fate,2019,18+,6.2,81,Action & Adventure,0,1
1,Gemini Man,2019,13+,5.7,74,Action & Adventure,0,1
2,Rambo: Last Blood,2019,18+,6.1,72,Action & Adventure,0,1
3,The Courier,2019,18+,4.9,50,Action & Adventure,0,1
4,Crawl,2019,18+,6.1,79,Action & Adventure,0,1
...,...,...,...,...,...,...,...,...
24659,Mama's Boy,2018,NaN,4.9,33,Drama,1,0
24660,I Am Jonas,2018,NaN,7.0,52,Drama,1,0
24661,An Unremarkable Christmas,2020,NaN,3.6,41,Drama,1,0
24662,BlackRose,2018,NaN,NaN,na,Drama,1,0
24663,A Very Special Drew,2000,NaN,8.0,41,Drama,1,0